name: Terraform
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    docker: 
      - image: cimg/base:2020.01
    context: aws-credentials
    runs-on: ubuntu-latest

    steps:

    - add_ssh_keys:
        fingerprints:
          - "8a:a9:e1:6b:71:1f:f3:8b:33:91:6c:f9:91:9a:17:53"

    - run:
        command: |
          mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          git clone git@github.com:s3679389/sdo-ass2.git

    - run: 
        name: Checkout master
        command: |
          cd sdo-ass2
          git checkout master

    - run: 
        name: Download AWS Config
        command: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -q awscliv2.zip && sudo ./aws/install
    
    - run: 
        name: Setup AWS CLI
        command: |
          aws configure set aws_access_key_id ${AWS_ACCESS_KEY} &&
          aws configure set aws_secret_access_key ${AWS_SECRET_KEY} && 
          aws configure set aws_access_session_token ${AWS_SESSION_TOKEN} && 
          aws configure set region ${AWS_REGION} 
        shell: sh

    - run: 
        name: Install Terraform
        command: |
          wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip

    - run: 
        name: Unzip Terraform Package
        command: |
          unzip -o terraform_0.12.24_linux_amd64.zip
          sudo mv terraform /usr/local/bin
    - run: 
        name: Init Terraform
        command: |
          rm -rf .terraform/ && terraform init

    - run: 
        name: Execute application
        no_output_timeout: 30m
        command: | 
          cd sdo-ass2
          make up
