version: 2.1
commands:
  setup-cd:
    steps:
    - run: 
        name: Configure environment
        command: |
          # install terraform
          curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
          sudo unzip terraform.zip -d /usr/local/bin/
          
          # instll helm
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash


jobs:
  build:
    machine: true
    environment:
      ECR: 724066712853.dkr.ecr.us-east-1.amazonaws.com
      reponame: app
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: |
            # install AWS CLI
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            # instll helm
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - run: 
          name: build docker image & push to registry
          command: |
            mkdir artifacts
            export IMAGE_TAG=${ECR}/${reponame}:${CIRCLE_SHA1}
            echo ${IMAGE_TAG} > artifacts/image.txt
            docker build -t ${IMAGE_TAG} .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR}
            docker push ${IMAGE_TAG}
      
      - run: 
          name: build helm package
          command: |
            cd helm 
            helm package techtestapp --app-version ${CIRCLE_SHA1}
            mv techtestapp-0.1.0.tgz ../artifacts/techtestapp.tgz 

      - run: 
          name: package up iac and scipts
          command: |
            cp -r infra artifacts/infra
            cp smoketest.sh artifacts/smoketest.sh
      
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

workflows:
  version: 2
  pipeline:
    jobs:
      - build