name: Terraform
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c7:31:08:c1:28:8b:b9:39:e1:68:6c:83:6d:31:e4:9c"

jobs:
  build:
    docker: 
      - image: cimg/base:2020.01
    context: aws-credentials
    runs-on: ubuntu-latest

    steps:

    - run: 
        name: Fetch repo
        command: |
          'git clone git@github.com:s3679389/sdo-ass2.git'

    - run: 
        name: Checkout master
        command: |
          'git checkout master'

    - run: 
        name: Download AWS Config
        command: |
          '(curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -q awscliv2.zip && sudo ./aws/install)'
        shell: sh
    
    - run: 
        name: Setup AWS CLI
        command: |
          'aws configure set aws_access_key_id ${{AWS_ACCESS_KEY}} &&
            aws configure set aws_secret_access_key ${{AWS_SECRET_KEY}} && 
            aws configure set region ${{AWS_REGION}}'
        shell: sh

    - run: 
        name: Install Terraform
        command: |
          'wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip'

    - run: 
        name: Unzip Terraform Package
        command: |
          'unzip -o terraform_0.12.24_linux_amd64.zip'

    - run: 
        name: Init Terraform
        command: |
          'rm -rf .terraform/ && terraform init'

    
    - run: 
        name: Execute
        command: | 
          'make up'
