- name: Deploy Application
  hosts: all
  become: yes
  become_method: sudo
  vars:
  tasks:

    - name: Create an app folder
      file:
        path: /etc/app
        state: directory

    - name: Unarchive application
      unarchive:
        src: https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_linux64.zip
        dest: /etc/app
        remote_src: yes

    - name: Update Database endpoint
      template:
        src: ./templates/database_rendered.tpl
        dest: /etc/app/dist/conf.toml

    - name: seed data to database
      shell: |
        cd /etc/app/dist
        ./TechTestApp updatedb -s
    
    - name: create service 
      template:
        src: ./templates/test.tpl
        dest: /etc/systemd/system/test.service
    
    - name: start serve
      systemd:
        daemon_reload: yes
        name: test
        state: started
        enabled: yes
      become: yes
      become_method: sudo



    
  