- name: Deploy Application
  hosts: all
  become: yes
  become_method: sudo
  vars:
  tasks:

    - name: Unarchive application
      unarchive:
        src: https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_linux64.zip
        dest: /etc
        remote_src: yes

    - name: Update Database endpoint
      shell: | 
        cd ../infra
        terraform output database_template
      register: database_output
      delegate_to: localhost

    - copy: 
        content: "{{database_output.stdout}}"
        dest: /etc/dist/conf.toml
    
    - name: create service 
      template:
        src: ./templates/test.tpl
        dest: /etc/systemd/system/test.service
    
    - name: start serve
      systemd:
        daemon_reload: yes
        name: test
        state: started
        enabled: yes
      become: yes
      become_method: sudo



    
  